# Generated by Django 5.0.3 on 2025-08-16 09:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happ', '0015_profile_last_checkin_date_profile_points_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_checkin_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='points',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rewards',
        ),
        migrations.CreateModel(
            name='RewardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CHECKIN', 'Daily check-in')], max_length=20)),
                ('points', models.IntegerField(default=0)),
                ('awarded_on', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='LoginHistory',
        ),
        migrations.AddConstraint(
            model_name='rewardtransaction',
            constraint=models.UniqueConstraint(fields=('user', 'kind', 'awarded_on'), name='unique_daily_checkin'),
        ),
    ]
