# Generated by Django 5.0.3 on 2025-08-16 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('happ', '0015_doctornote'),
        ('happ', '0017_rewardtier_rewardclaim'),
    ]

    operations = [
    ]
