# Generated by Django 5.0.1 on 2025-09-27 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("happ", "0018_merge_0015_doctornote_0017_rewardtier_rewardclaim"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="patient_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=8,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{8}$", "Enter exactly 8 digits."
                    )
                ],
            ),
        ),
    ]
